version: 0.2

phases:
  install:
    runtime_versions:
      java: corretto17
  build:
    commands:
      - mvn clean package
      - echo "Build successful!"
  post_build:
    commands:
      - echo "Moving JAR file to the root..."
      - mv target/social-media-blog-app-0.0.1-SNAPSHOT.jar application.jar

artifacts:
  files:
    - application.jar
  discard-paths: no
