version: 0.2

phases:
  install:
    runtime_versions:
      java: corretto17
    commands:
      - echo install
    pre_build:
      commands:
          -echo pre_build
    build:
      commands:
        - mvn clean package
        - echo build
    post_build:
      commands:
        - echo post_build
        - mv target/social-media-blog-app-0.0.1-SNAPSHOT.jar # Move JAR to root

artifacts:
  files:
    - target/social-media-blog-app-0.0.1-SNAPSHOT.jar   # Ensure JAR is at root
    - procfile          # Include Procfile (optional, see below)
  discard-paths: yes